version: '2'

services:
  proxy:
    image: pixelfordinner/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/proxy/conf:/etc/nginx/conf.d
      - ./config/proxy/vhost:/etc/nginx/vhost.d:ro
      - ./config/proxy/certs:/etc/nginx/certs:ro
  app:
    image: syncforscience/reference-app
    environment:
     - SYNCHRONIZER_HOST="http://research-app-api:5000"
    volumes:
     - ./config/app/fixtures.yml:/usr/src/app/researchapp/fixtures.yml
  api:
    image: syncforscience/reference-api
    restart: always
    volumes:
     - hapi.db:/hapi/target
  tests:
    image: syncforscience/reference-tests
    volumes:
      - tests.db:/usr/src/app/testsuite/db
      - ./config/tests/:/usr/src/app/config
  research-app-api:
    image: syncforscience/research-app-api
    volumes:
      - research-app-api.db:/usr/src/app/research_app/db
      - ./config/research-app-api/providers.yml:/usr/src/app/providers.yml
    entrypoint: ""
    command: "./runserver.sh"

volumes:
  hapi.db: {}
  research-app-api.db: {}
  tests.db: {}
