version: '2'

services:
  proxy:
    image: nginx
    restart: always
    depends_on:
      - tests
      - app
    ports:
      # bind to loopback only to keep this locked down
      - "127.0.0.1:443:443"
    volumes:
      - ./config/proxy/certs:/etc/nginx/certs
      - ./config/proxy/conf.d:/etc/nginx/conf.d
  app:
    image: syncforscience/reference-app:latest
    environment:
     - SYNCHRONIZER_HOST=http://research-app-api:5000
    volumes:
     - ./config/app/fixtures.yml:/usr/src/app/researchapp/fixtures.yml
  api:
    image: syncforscience/reference-api:latest
    restart: always
    volumes:
     - hapi.db:/hapi/target
  tests:
    image: syncforscience/reference-tests:latest
    environment:
     - BASE_URL=https://test-suite.pilot-prep.syncfor.science
     - API_SERVER_DSTU2=http://api:8080/baseDstu2
     - API_SERVER_STU3=http://api-stu3:8080/baseDstu3
     - BLOOM_FILTER_URL=https://s3.amazonaws.com/fhir-code-validation/codes.bf
    volumes:
      - tests.db:/usr/src/app/testsuite/db
      - ./config/tests/:/usr/src/app/config
  research-app-api:
    image: syncforscience/research-app-api:latest
    environment:
      FLASK_DEBUG: 1
    volumes:
      - research-app-api.db:/usr/src/app/research_app/db
      - ./config/research-app-api/providers.yml:/usr/src/app/providers.yml
    entrypoint: ""
    command: "./runserver.sh"

volumes:
  hapi.db: {}
  research-app-api.db: {}
  tests.db: {}
